export const actionsUrl = 'https://www.racinesderesilience.org/api/actions.php';
export const headerHeight = 50;
export const gitHubLink = 'https://github.com/Terractiva/racines-de-resilience';
export const nbFilterResultsShowed = 6;
export const treeFontSize = 0.004; // Taille du texte en % de la hauteur de l'arrière plan
export const treeSubcategoryFontSize = 0.006;
export const zoomIncrement = 0.5;
export const zoomMax = 10;
export const zoomMin = 1;
