title: Page par défaut
icon: 📝

tabs:
  content:
    label: Contenu
    icon: page
    sections:
      heading:
        extends: sections/section-hero
      layout:
        extends: sections/page-layout

  settings:
    label: Paramètres
    icon: settings
    sections:
      settings:
        extends: sections/page-settings
