columns:
  - width:
    sections:
      siteHomeMemo:
        extends: sections/memo

  - width:
    fields:
      miscHeadline:
        type: headline
        label: Divers
        numbered: false
  - width:
    fields:
      airtableFormUrl:
        type: url
        label: Formulaire d'ajout d'action
        required: true
      partners:
        type: structure
        label: Partenaires
        columns:
          name: true
        fields:
          logo:
            type: files
            label: Logo
            width: 1/6
            help: L'image sera automatiquement optimisée
            max: 1
            layout: cards
            size: tiny
            uploads: image
            image:
              back: white
          name:
            type: text
            label: Nom
            width: 5/12
            required: true
            autofocus: true
          url:
            type: url
            label: Lien
            width: 5/12

  - width:
    fields:
      navHeadline:
        type: headline
        label: En-tête
        numbered: false
  - width:
    fields:
      logo:
        type: files
        label: Logo
        width: 1/3
        required: true
        help: L'image sera automatiquement optimisée
        max: 1
        layout: cards
        size: tiny
        uploads: image
        image:
          back: white
      navLinks:
        extends: fields/links
        width: 1/3
      navButtons:
        extends: fields/buttons
        width: 1/3

  - width:
    fields:
      footerHeadline:
        type: headline
        label: Pied de page
        numbered: false
  - width: 1/3
    fields:
      footerSocialHeading:
        type: text
        label: Réseaux sociaux - Titre
        required: true
      footerSocialLinks:
        type: structure
        label: Réseaux sociaux - Liens
        fields:
          label:
            type: text
            label: Libellé
            required: true
          url:
            type: url
            label: Lien
            required: true
  - width: 1/3
    sections:
      footerSitemapFields:
        type: fields
        fields:
          footerSitemapHeading:
            type: text
            label: Plan - Titre
            required: true
      footerSitemapPages:
        type: pages
        label: Plan - Pages
        help: Seules les pages disponibles dans la langue sélectionnée seront affichées
        status: listed
        create: false
        image:
          query: false
  - width: 1/3
    fields:
      footerFreeText:
        type: writer
        label: Texte libre
        required: true
        nodes: false
  - width:
    fields:
      footerCopyright:
        type: writer
        label: Copyright
        required: true
        nodes: false
