tabs:
  home:
    label: Accueil
    icon: home
    extends: sections/site-tab-home

  statistics:
    label: Statistiques
    icon: chart
    extends: sections/site-tab-statistics

  files:
    label: Fichiers
    icon: file
    extends: sections/site-tab-files

  settings:
    label: Paramètres
    icon: settings
    extends: sections/site-tab-settings
