columns:
  analytics:
    width: 2/3
    sections:
      todo:
        type: info
        label: Statistiques
        text: "TODO: insérer les statistiques Matomo"

  pages:
    width: 1/3
    sections:
      pages:
        type: pages
        info: "{{ model.showInMenu.boolToString('dans le menu') }}"
        create: default
