name: Construction et déploiement du site

on:
  push:
    branches: [site]
    paths-ignore:
      - '.github/workflows/deploy-api.yml'
      - 'src/api/actions.php'
  pull_request:
    branches: [site]
    paths-ignore:
      - '.github/workflows/deploy-api.yml'
      - 'src/api/actions.php'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Construction
        run: npm ci && npm run build

      - name: Déploiement
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: ${{ secrets.ftp_server }}
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}
          local-dir: build/
